### ISSUE TITLE
Data export inaccurate

### ISSUE THREAD

**Issue by dirtymike0330** [Bango1999/SLSC#3]
I assume I have done something incorrectly, but I believe I got the S3 and SLSC stuff running correctly. However, something is lost during the export to the S3 server. On the website, it does not display all of the Slmodstats information. Specifically, only the following planes: A10, F15, F5, F86, P51, M2k, Spit, BF109 are showing on the table despite us flying Hornets, F14s, etc. Also doesn't seem to accurately reflect flight hours, kills, etc. User names ARE populating, so I think I am close.

**Comment by Bango1999** [comment]
Issue is addressed [here](https://github.com/Bango1999/S3/issues/10#issuecomment-914454141).
